### DISCUSSION TITLE
Retype on Jamstack.org

### DISCUSSION THREAD

**Discussion by DannyBen** [retypeapp/retype#108] [General]
A nice, sorted list of static site generators:
https://jamstack.org/generators/

Would be nice to have Retype here ([contribution instructions](https://github.com/jamstack/jamstack.org#contribute-a-site-example)).

P.S. I went to look for other site generators, because I am looking for a non-documentation generator, that is as nice as retype...

**Comment by fabriciomurta** [comment]
Looks easy enough to fill in a pull request. I'll use our next group meeting to decide together what to fill in the features list. I doubt there will be any reason not to. Thanks!

**Comment by geoffreymcgill** [comment]
Thanks for the suggestion. I will investigate. 

> because I am looking for a non-documentation generator

What are your requirements?

**Reply by DannyBen** [reply]
> What are your requirements?

There are tons of static site generators. For the most part, they all either give you full flexibility (which means you need to choose your own css, develop your own layouts etc), or they give you "themes" which are usually outdated and look the same-ish.

Ideally, I would want to configure a site with only YAML and Markdown - like we do on Retype. Imagine such a YAML:

```yaml
colors:
  primary: ...
  secondary: ...

pages:
  about:
    path: /about
    layout: page-with-large-hero
    nav:
      - services
      - documentation
    hero:
      title: ...
      subtitle: ...
      color: secondary
    body:
      - intro.md
      - about-me.md

  services:
    # ...
  documentation:
    # ...
```

Of course, YAML is just one way of defining things. My point is, I want to be semantic, and not deal with archaic HTML tags and styling decisions.

Imagine a "new form of HTML" where you do:

```slim
nav
  right
    brand-link
  left
    services
    documentation
    
hero
  title The Secret
  subtitle There is no spoon

body
  markdown:
    # Welcome to my site

    Some text
```

The slim template engine is close to this syntax, only except the new, invented, tags.

But until such a tool is invented, I am settling on the next best thing, with these mandatory requirements:

- [x] Support `slim` templates, which is the "complete work of art" when it comes to template engines in my mind.
- [x] Support `scss` compilation out of the box.
- [x] No "webpack" or other JS nonsense.
- [x] Either no themes at all, or simple and modern themes.
- [x] Both input and output folders must be simple and logical
- [x] Easy configuration
- [x] Clean and canonical documentation (no docs for different versions etc).
- [x] Extra points for Ruby-based tools.

My shortlist is:

- Jekyll - the grand-daddy of site generators, ruled out, does not meet some of the criteria.
- Nanoc - almost perfect, but its `scss` compilation uses a Ruby library which is EOL, maintainers seem to have lost interest.
- Middleman - best so far - ticks all the boxes of the above requirements.

Do you regret asking?... :)
