### DISCUSSION TITLE
Gravatars

### DISCUSSION THREAD

**Discussion by VeeBack** [retypeapp/retype#140] [Ideas]
Hey!

It would be great if we could enable using Gravatars as the avatar by default, using the email provided in the author
```
---
author:
  - name: Victor Bäck
    email: vb@manhunt.gg
  - name: Drekec
    email: drekec@manhunt.gg
---
```

With this, it would also be great to be able to use the default avatar option that Gravatar allows with the `d` parameter when an email doesn't have an avatar registered. Example [with valid email](https://www.gravatar.com/avatar/5663eaccee145f9edd23a3601a1c6e3c?d=https%3A%2F%2Fstatic-cdn.manhunt.gg%2Fmanhunt.png), and [without](https://www.gravatar.com/avatar/f3102edf6fa5017b29f25c5953c6e059?d=https%3A%2F%2Fstatic-cdn.manhunt.gg%2Fmanhunt.png).
