### DISCUSSION TITLE
Codeblock line highlighting

### DISCUSSION THREAD

**Discussion by dwbelliston** [retypeapp/retype#176] [Ideas]
Would be awesome to be able to highlight lines in a code block to call out specific lines.

thanks!

```
  """yaml # hl_lines="9 14 24 25 26 28"
  CloudVelumAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
          ActionsEnabled: Boolean
          AlarmActions:
              - String
          AlarmDescription: String
          AlarmName: String
          ComparisonOperator: String
          DatapointsToAlarm: Integer
          Dimensions:
              - Dimension
          EvaluateLowSampleCountPercentile: String
          EvaluationPeriods: Integer
          ExtendedStatistic: String
          InsufficientDataActions:
              - String
          MetricName: String
          Metrics:
              - MetricDataQuery
          Namespace: String
          OKActions:
              - String
          Period: Integer
          Statistic: String
          Threshold: Double
          ThresholdMetricId: String
          TreatMissingData: String
          Unit: String
   """

```
