### DISCUSSION TITLE
Multiple nav links

### DISCUSSION THREAD

**Discussion by RickCogley** [retypeapp/retype#211] [Q&A] [answered]
Is it possible to specify multiple nav links? If so could someone please advise the yaml syntax? Tia!

**Comment by geoffreymcgill** [comment]
Additional custom links in the left side-bar navigation? for instance, linking to an external site? If yes, at the moment that functionality is not available, but it's something we have planned on adding for a long time, just never had the time or priority to get to it yet.

I believe it is actually possible right now, but only using a `SUMMARY.md` file to manually define the navigation, which is not ideal.

We just need to build in an easy to use config option for inserting additional navigation link items.

**Comment by geoffreymcgill** [comment]
I just thought of something. It might be possible by creating an empty page and adding the [`redirect`](https://retype.com/configuration/page/#redirect) config. The page would participate in the navigation hierarchy, but when anyone visits the page, the user would be automatically redirected to your `redirect` location.

**Reply by RickCogley** [reply]
Thanks for the answer. I mean, in the top nav or footer. I tried using the links config param, but it caused an error.

**Reply by AndreyChechel** [reply]
It should be possible with the following syntax.
If it still doesn't work, please share your configuration and the error you got, so we can investigate.

```yml
links:
  - text: Home
    link: /readme.md

  - text: About
    link: /about.md

footer:
  links:
    - text: Home
      link: /readme.md

    - text: About
      link: /about.md
```
