### DISCUSSION TITLE
Is it possible to add a Google tag?

### DISCUSSION THREAD

**Discussion by jorikfon** [retypeapp/retype#234] [Q&A]
I want to add something like the Yandex Metrika, Facebook Pixel, and live chat as you have on the retype.com
Usually, I use a GTM to do it.

**Comment by fabriciomurta** [comment]
I think you are looking to an [integration](https://retype.com/configuration/project/#integrations), right? We don't support "google tags" but [we do support adding tags to documents](https://retype.com/configuration/page/#tags), is this by any chance what you need? Or do you want tags to have specific code to be handled by google services?

**Reply by jorikfon** [reply]
This one https://tagmanager.google.com/

I see in the sources of your site it is included.

**Reply by geoffreymcgill** [reply]
Just configure your [`integrations.googleAnalytics.id`](https://retype.com/configuration/project/#googleanalytics) value. Retype should automatically add the proper TagManager reference to your website.

```yml
integrations:
  googleAnalytics:
    id: <your-tag-manager-code-here>
```

We should probably add `googleTagManager` as another option. Or as a proposal, we could revise to the following structure:

```yml
integrations:
  google:
    analytics: <your-code-here>
    tagManager: <your-code-here>
```

**Reply by jorikfon** [reply]
I did it, but the tag didn't start.

Look...

``` yaml
integrations:
  googleAnalytics:
    id: GTM-KXBHF8J
```

On every page of my website it adds following code:
``` html
  <script async src="https://www.googletagmanager.com/gtag/js?id=GTM-KXBHF8J"></script>
  <script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'GTM-KXBHF8J');</script>

```

I see the google tag manager loaded by my browser, but it doesn't start.

If I add on the page the next script, instead of yours, it works! 

``` html
 <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KXBHF8J');</script>
<!-- End Google Tag Manager -->
```

It runs all scripts included on the Google Tags Manager website at my tag.

Can you check what is wrong?

**Reply by geoffreymcgill** [reply]
Thanks for the update. We will look into this right away and implement a fix. Once we have a fix in place, we will figure out what release the update will go into.

**Reply by geoffreymcgill** [reply]
[Google Tag Manager](https://retype.com/configuration/project/#googleantagmanager) integration is now available with Retype [`v2.0.0-preview`](https://github.com/retypeapp/retype/discussions/287#discussioncomment-2321442) and should be generally available next week with the final `v2.0.0` release.

The configuration within your projects `retype.yml` file would be:

```yml
integrations:
  googleTagManager:
    id: <your-tag-manager-code-here>
```

For example:

```yml
integrations:
  googleTagManager:
    id: GTM-KXBHF8J
```

If you have a chance, we would certainly appreciate you testing the `v2.0.0-preview` release and confirming that the Google Tag Manager integration is working as expected.

Hope this helps.

**Update:** The [`googleTagManager`](https://retype.com/configuration/project/#googletagmanager) configuration docs have been published.
