### DISCUSSION TITLE
error with github actions - later resolved

### DISCUSSION THREAD

**Discussion by TimHeckel** [retypeapp/retype#248] [Q&A] [answered]
Hey all - love this project! But when using the github actions, I received this error when running the below `.github/workflows/build-for-retype.yml` action (and I fixed it below):

`Error : .github#L1 the 'uses' attribute must be a path, a Docker image, or owner/repo@ref`

```
name: build-for-retype
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to the retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: retypeapp/action-build

      - uses: retypeapp/action-github-pages
        with:
          branch: retype
          update-branch: true
```

Then I noticed the error expected a version number `@ref` for the repositories in the `uses` clause, so I added:

```
     - uses: retypeapp/action-build@v1

      - uses: retypeapp/action-github-pages@v1.11.2
        with:
          branch: retype
          update-branch: true
```

And repushed the branch, and it worked (the `retype` branch was correctly published from the source I pushed). Not sure if this is helpful to others, but thought I'd share.

Thanks!
