### DISCUSSION TITLE
yaml api configuration format

### DISCUSSION THREAD

**Discussion by ApolonTorq** [retypeapp/retype#252] [Q&A] [answered]
What's the format for configuring the API section of retype.yaml and can you provide some examples?
It looks like its changed since the last version I ran API docs generation with retype.

**Comment by AndreyChechel** [comment, marked as answer]
Hi @ApolonTorq 

Here's the actual API configuration section structure:

| Option                             | Type          | Default value              | Description                                                                                                                     |
| ---------------------------------- | ------------- | -------------------------- | ------------------------------------------------------------------------------------------------------------------------------- |
| `api`                              | `object`      |                            | API configuration                                                                                                               |
| `api.input`                        | `string`      |                            | Path to a project file, or a project directory                                                                                  |
| `api.output`                       | `string`      | `./api`                    | Custom path to the API output directory. Relative to `output`                                                                   |
| `api.projects`                     | `array`       |                            | API Project configuration                                                                                                       |
| `api.projects[].input`             | `string`      |                            | Path to a project file, or a project directory                                                                                  |
| `api.projects[].output`            | `string`      |                            | Custom path to the API output directory. Relative to `output`                                                                   |

The `api.input` and `api.output` configs act differently depending on whether the `api.projects` config is specified or not:
- if the `api.projects` is specified, then the `api.input` and `api.output` provide default values for the `projects` entries (unless a project entry declares it's own `input`/`output` so the default values are not used)
- if the `api.projects` is not specified, the `api.input` and `api.output` act as a single project configuration

Please see the examples below.

### A single project

```yml
api:
  input: "../Retype.App/"
  output: "./api"
```

The same configuration but using the `projects` config:
```yml
api:
  projects:
    - input: "../Retype.App/"
      output: "./api"
```

### Multiple projects

```yml
api:
  projects:
    - input: "../Retype.App/"
      output: "./api"
    - input: "../Retype.App.Tests/"
      output: "./api"
```

Since the both project in the sample above use the same `output` value, the configuration can be simplified by getting advantage of the top-level configs acting as the default values for the `projects` entries:

```yml
api:
  output: "./api"
  projects:
    - input: "../Retype.App/"
    - input: "../Retype.App.Tests/"
```
