### DISCUSSION TITLE
How to configure github pages to use my retype page?

### DISCUSSION THREAD

**Discussion by fstrauf** [retypeapp/retype#275] [Q&A] [answered]
Hi folks,

i'd love to use retype for my project and have gone through step 1 here:

https://retype.com/guides/github-actions/

When I get to step 2 here:

https://retype.com/hosting/github-pages/#step-2-configure-github-pages 

I'm not really sure what to do. Here is how it currently looks:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/11333532/154567335-9a294f04-86eb-4290-8518-cd158f24ab1c.png">

Appreciate your help.

**Comment by geoffreymcgill** [comment, marked as answer]
I think you just need to add a `retype.yml` file to your project and set `url: fstrauf.github.io/tokenomicsDAO` within that file. 

See https://retype.com/configuration/project/.

A basic `retype.yml` for your project should be:

```yml
input: .
url: fstrauf.github.io/tokenomicsDAO
branding:
  title: TokenomicsDAO
  label: Docs
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."
```

Hope this helps.

**Reply by DannyBen** [reply]
Yes, it seems like the site is already published (https://fstrauf.github.io/tokenomicsDAO/), but due to the missing configuration file, it does not find its assets.

**Reply by geoffreymcgill** [reply]
If you want to use your `/docs` folder for you documentation project, configure [`input: ./docs`](https://retype.com/configuration/project/#input) in your `retype.yml` project configuration file.

Without that config, Retype will start looking for `.md` pages within the root of your repo (at the same level as the `retype.yml`).

**Reply by geoffreymcgill** [reply]
Here's the reason the `url` and that `/tokenomicsDAO` subfolder appended to the end is required:

https://retype.com/hosting/github-pages/#set-a-url

**Reply by fstrauf** [reply]
So I've done that and added this to my yml. But somehow the css doesn't really load. Any idea?

<img width="779" alt="image" src="https://user-images.githubusercontent.com/11333532/154582998-a40117f0-adef-42a8-abd5-b48338efedb2.png">

**Reply by fstrauf** [reply]
this is my yml https://github.com/fstrauf/tokenomicsDAO/blob/main/.github/workflows/retype.yml

**Reply by geoffreymcgill** [reply]
There are two different `retype.yml` files. 

First is for the project configuration that should be in your repo root at `/retype.yml`. 

Second is the GitHub Action configuration, stored at `/.github/workflows/retype.yml`. 

You have merged the two together, so the following section needs to be moved out of `.github/workflows/retype.yml` and into the root `retype.yml`:

```yml
input: ./docs
url: fstrauf.github.io/tokenomicsDAO
branding:
  title: TokenomicsDAO
  label: Docs
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."
```

We have created this confusion by naming both files `retype.yml`, so I'm going to change that in our docs and samples.

The `.github/workflows/retype.yml` file can be named anything and could be renamed to `github/workflows/retype-action.yml`.
