### DISCUSSION TITLE
Old page width

### DISCUSSION THREAD

**Discussion by titusgahissy** [retypeapp/retype#294] [General]
Hello,

With the new version `v2` is it possible to adjust the container `max-width`?  I checked the docs and couldn't see such an option. Some people like a more compact layout. It'd be great to give the option to control that `width`. 
```css
/* v1 */
.container {
    max-width: 1400px;
}

```

```css
/* v2 */
.container {
    max-width: 1800px;
}
```
Thanks!
