### DISCUSSION TITLE
How to serve Retype at www.my-site.com/docs/

### DISCUSSION THREAD

**Discussion by RoryGraman** [retypeapp/retype#423] [General]
Hello!

I have a react app for an ongoing project that will be hosted at https://conveyor.finance. There is already a landing page set at the home directory, and an an additional page hosted at '/app/. 

I really like the interface of Retype, and want to use it for the documentation of our site, and want to set it up where it is served at https://conveyor.finance/docs/.

All the markdown files will be stored in the project (not served from github pages), but I'm having difficulty having it serve from the /docs/ URL when running a local version of the site.

Expected results: When running `yarn start` from the root directory, the website should render at `localhost:3000` and `localhost:3000/app`, which is already happening, but it should also render Retype at `localhost:3000/docs`. I've tried updating the port, but no joy on having everything render/export correctly

I have a 'docs' folder in the root directory of my project, and it does currently serve using `retype watch` at `localhost:5000/docs`

current structure

| build
| public
| src
| docs (retype) 
retype.yml

retype.yml

```
input: ./docs/
output: .retype
url: https://conveyor.finance
branding:
  title: ConveyorFinance
  label: Docs
links:
- text: Getting Started
  link: https://retype.com/guides/getting-started/
footer:
  copyright: "&copy; Copyright {{ year }} - [Conveyor Labs](https://conveyorlabs.org). All rights reserved."
```
any help would be appreciated!
