### DISCUSSION TITLE
navbar

### DISCUSSION THREAD

**Discussion by noraj** [retypeapp/retype#48] [Q&A]
It would be easier to have a tree structure written in `navbar.yaml` or in the global config file

eg.

```yaml
nav:
  - Home: index.md
  - Cheatsheet:
    - 'Basic concepts': 'cheatsheet/basic-concepts.md'
    - 'Control structures': 'cheatsheet/control-structures.md'
    - Collections: 'cheatsheet/collections.md'
    - Methods: 'cheatsheet/methods.md'
    - 'Object oriented programming': 'cheatsheet/object-oriented-programming.md'
    - 'Modules, mixins and standard classes': 'cheatsheet/modules-mixins-standard-classes.md'
    - Files: 'cheatsheet/files.md'
  - About: 'about.md'
```

rather than having to play with the order meta-data in all files.

**Comment by geoffreymcgill** [comment]
This functionality is currently supported using a `SUMMARY.md` page. The `SUMMARY.md` page would be added to the root of your project (at the same level as your `index.md`).

Your configuration would be revised to:

```md
- [Home](index.md)

## Cheatsheet

- [Basic concepts](cheatsheet/basic-concepts.md)
- [Control structures](cheatsheet/control-structures.md)
- [Collections](cheatsheet/collections.md)
- [Methods](cheatsheet/methods.md)
- [Object oriented programming](cheatsheet/object-oriented-programming.md)
- [Modules, mixins and standard classes](cheatsheet/modules-mixins-standard-classes.md)
- [Files](cheatsheet/files.md)

---

- [About](about.md)
```

**Reply by noraj** [reply]
1. I didn't see anything about `SUMMARY.md` in the documentation
2. Using `SUMMARY.md` ignore all metadata from each pages (icon, collapse, etc.)

**Comment by geoffreymcgill** [comment]
Retype could also easily support the configuration using `navbar.yml` or `SUMMARY.yml`, although I'm not sure that would be necessary when `SUMMARY.md` covers that scenario?

@noraj Do you know of another static-generator app that uses the `navbar.yml` syntax?

**Reply by noraj** [reply]
- Docusaurus v2 (beta) https://docusaurus.io/docs/api/themes/configuration#navbar
- Docusaurus v1 https://v1.docusaurus.io/docs/en/navigation#adding-documents-to-a-sidebar
- MkDocs https://www.mkdocs.org/user-guide/configuration/#nav

**Reply by geoffreymcgill** [reply]
We are going to improve our support for the Docusaurus and MkDocs config files. These files will likely only be read and mapped to `retype.json` when the `retype init` command is called. The command `retype init` is also run the first time `retype watch` is called.

It's going to take us some time to work out all the requirements, so I'm not sure the new functionality will make it into `v1.8.0`, but we will try our best. There's some important updates ahead in line before we can tackle the Docusaurus and MkDocs config files.

**Reply by noraj** [reply]
Having this nav possibility is nice when a precise order is required (sorting with priority would be too complex and unmaintainable) but when order is not importing having this automatic sorting is very nice :)

**Reply by DannyBen** [reply]
I for one am also struggling with ordering issues (I opened #90).

I think that `SUMMARY.md` is not a great option (is it even documented?):

1. It forces you to rewrite page titles.
2. It does not obey icons.
3. Its name seems like a relic from older similar products.

I too would prefer a YAML file, named `order.yml` (not `navbar` nor `summary`, since it should also influence the next/prev links).

- This YAML should just be a nested array, of `*.md` filenames (no labels), and array items that are a hash, means its a folder.
- Its result should read titles and icons from the markdown file itself, as if it the `order.yml` was never used.
- The navbar should still show files that do not appear in this `order.yml` file - these documents should appear after all the ordered ones. This way it will be immediately obvious when I add a new document, that I need to order it.

For example:

```yaml
- README.md
- installation.md
- usage: # <- folder
  - README.md
  - getting-started.md
- reference:
  - README.md
  - command-reference.md
  - action-reference.md
- support.md # <- back to showing a file from root folder
```

This I feel is the most intuitive and minimal way to write this, without having to repeat information that exists elsewhere.
