### DISCUSSION TITLE
Multiple version builds

### DISCUSSION THREAD

**Discussion by DannyBen** [retypeapp/retype#484] [Ideas]
I am pretty sure I saw a discussion on this somewhere, but I could not find it.

I have reached a point in my tools documentation where it is desired to have both a documentation for the current version, and for an older version. 

For local use - this is not a problem, as I have different tags in the same repository. But for deployment (I am using the GitHub Retype action) - it is a different story.

I would love to be able to have mysite.com/ show the latest version, and mysite.com/0.12.0/ show a different version.

Ideally, I would love to be able to not change anything in my own code, and instead, just tell the Retype GitHub action to do it, like so:

```yaml
jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest

    steps:
      # ... setup and .NET steps removed for brevity ....

      - name: Build site
        uses: retypeapp/action-build@v2
        with:
          # build from the same repo's ref 'v0.12.0' and make it available
          # under the mysite.com/v0.12.0 directory
          also-build: v0.12.0
      
      # ... publish action unchanged, since the built site already has the needed files ...
```

I know this is not implemented now - but can something like this be done on my side now without too much hacking?
