### DISCUSSION TITLE
Trying to setup retype on Github Pages and failing

### DISCUSSION THREAD

**Discussion by Ravencentric** [retypeapp/retype#500] [Q&A]
https://github.com/Ravencentric/retype-test
https://ravencentric.github.io/retype-test/

I did follow https://retype.com/guides/github-actions/ but I can't seem to get it working

**Comment by geoffreymcgill** [comment]
It looks like you are committing files directly to the `retype` branch and that is conflicting with Retype and the GitHub Action.

Try the following steps:

1. Double check that you have the GitHub Pages configured correctly. I cannot see that page in your repo, but from what I can tell, you have GitHub Pages configured correctly, but it would be good to just double check.
![image](https://user-images.githubusercontent.com/62210/219949529-54ab2222-4d90-45ad-9004-53f1e00258e6.png)
2. Delete your `retype` branch. On your [branches](https://github.com/Ravencentric/retype-test/branches) page, you should see the `retype` branch and a 🗑️ icon on the far right of that line to delete the branch. The `retype` branch will be recreated when you make another change to your `main` branch.
3. Commit something to your `main` branch, such as making a change to the [`README.md`](https://github.com/Ravencentric/retype-test/blob/main/README.md) file. Only commit the change to the `main` branch, not the `retype` branch.

Everything else look good. 

Hope this helps.

**Comment by Ravencentric** [comment]
if i delete the retype branch then the github pages automatically turns off since the branch it was being built from was deleted. Even pushing anything to main doesnt seem to recreate `retype` branch

**Reply by geoffreymcgill** [reply]
It looks like GitHub has changed the default for **Workflow permission** when new repos are created. In order for Retype to create the `retype` branch and write the generated files into that branch, Retype needs to have write permissions. Previously, that was granted by default, but it appears GitHub has recently changed to `read` only permissions by default. 

The fix/work-around is simple by enabling the following setting:

Settings > Actions / General > Scroll to **Workflow permissions**

<img width="793" alt="Screen Shot 2023-02-21 at 1 53 16 PM" src="https://user-images.githubusercontent.com/62210/220456693-1076e287-9998-4852-9258-16dac2071aea.png">

We're doing some research into any other options we might have as an Action publisher, but it would appear our options are limited and any freshly created repos using Retype would need to enable **Read and write permissions** for the repo.

**Reply by geoffreymcgill** [reply]
We found that content write permissions can be granted on a per-Action basis, so you do not need to enable for the entire repo. 

Add the following `permissions` > `contents` config within the `jobs` > `publish` section of your `.github/workflows/retype-action.yml` file

```yml
    permissions:
      contents: write
```

Here is a new default `retype-action.yml` file.

```yml
name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
```

We have also updated the GitHub Action documentation on the retype.com website, see https://retype.com/guides/github-actions/#step-1-add-retype-actionyml-workflow

If you are using a `retype-action.yml` with a Retype license key and the `RETYPE_SECRET`, the default workflow configuration would now be the following:

```yml
name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_SECRET }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
```
