### DISCUSSION TITLE
Authors

### DISCUSSION THREAD

**Discussion by TiagoVXII** [retypeapp/retype#526] [Q&A] [answered]
I'm unable to put an avatar for the second author with this error:

Error in user YAML: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 4 column 3

can i get help please

**Comment by geoffreymcgill** [comment]
Can you share your `author` config here? That should help us reproduce the issue and then recommend a fix or work-around.

**Reply by TiagoVXII** [reply]
```
---
label: FAQ
icon: question
authors:
  - name: Flas4hPT
    avatar: https://avatars.githubusercontent.com/u/93576144?v=4
  - Eduardo
  avatar: https://cdn.discordapp.com/avatars/708797379016523837/bbc1d1c51a283201c04f14b7deb7dfcf.webp?size=4096&width=670&height=670
---
```

**Reply by geoffreymcgill** [reply, marked as answer]
Seems to work fine for me if I use `name: Eduardo` instead of just `Eduardo`. Here is the full sample:

```
---
label: FAQ
icon: question
authors:
  - name: Flas4hPT
    avatar: https://avatars.githubusercontent.com/u/93576144?v=4
  - name: Eduardo
    avatar: https://cdn.discordapp.com/avatars/708797379016523837/bbc1d1c51a283201c04f14b7deb7dfcf.webp?size=4096&width=670&height=670
---
```
