### DISCUSSION TITLE
Unable to Prevent Auto-Generated Azure SWA Workflow in `publish` Branch by `retypeapp/action-github-pages`

### DISCUSSION THREAD

**Discussion by JoelMTaylor** [retypeapp/retype#720] [Q&A] [answered]
### Description:
I'm using Retype to automate building and deploying my site via GitHub Actions. Specifically, I am using the `retypeapp/action-github-pages@latest` step in my `retype-build.yml` file. However, I'm encountering an issue where the `azure-SWA-HASH.yml` workflow is automatically being generated and committed to the `publish` branch.

#### Disclaimer
I am an amateur in this topic, and all comments should be taken with caution. I have done my best to get informed (through the Retype Docs and ChatGPT), but there may still be mistakes. I apologize in advance for any inaccuracies.

### Issues Faced:
1. **Auto-Created Azure SWA Workflow**:
   - The Retype build action (`retypeapp/action-github-pages@latest`) always deploys a workflow named **`azure-SWA-HASH.yml`** to the `.github/workflows/` directory of the `publish` branch.
   - The workflow was automatically created by Azure SWA and was at one time added to the repo. 

2. **Unable to Modify or Replace Workflow**:
   - I have attempted to modify the contents of the `azure-SWA-HASH.yml` file, but it either does not get updated or it gets overwritten with the original version on subsequent builds.
   - I also tried adding other workflows manually to the `publish` branch, but they do not persist—I'm always left with only the automatically generated **`azure-SWA-HASH.yml`** file after the build completes.

3. **GitIgnore Does Not Prevent Deployment**:
   - I added `.github/workflows/azure-publish.yml` and `.github/workflows/azure-SWA-HASH.yml` to my `.gitignore` file in the `main` branch, but these files still get created in the `publish` branch by the Retype GitHub Pages Action.

### Build Logs Snippet:
In the build logs of the for the step that has `retypeapp/action-build@latest`, I noticed the following:

```
Deploying resources:          ".github/workflows"
Deploying file:                    ".github/workflows/azure-SWA-HASH.yml"
Resources deployed:          ".github/workflows"
```

_This suggests that Retype is explicitly deploying this workflow, despite my attempts to change/ignore it._ 

### My Question:
- **Is it possible that the Retype action is automatically creating or updating the `azure-SWA-HASH.yml` workflow in the `publish` branch?** If so, how can I prevent or change this?
- Alternatively, **is there a way to control or configure the generated workflow so that it doesn't overwrite my changes or automatically get deployed?**

Any guidance on how to stop this automatic workflow generation or to have better control over the deployment configuration would be greatly appreciated.

---

### Context and Code
I have added this section to provide some code snippets that might be relevant. 

#### `retype-build.yml`
Note: the Retype action pushes to a custom branch `publish` not the default `retype`. This seems to work perfectly (specifically the retype build action) and successfully pushes the website to the `publish` branch.
```
name: Build and Push Website to Publish Branch

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  build:
    name: Build and Deploy to Publish Branch
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes to the `publish` branch

    steps:
      # Step 1: Check out the main branch
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main  # Explicitly check out the main branch

      # Step 2: Set up .NET for Retype
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      # Step 3: Build the website using Retype
      - name: Build Website
        uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_SECRET }}

      # Step 4: Deploy built website to the `publish` branch
      - name: Deploy to Publish Branch
        uses: retypeapp/action-github-pages@latest
        with:
          branch: publish  # Specify `publish` as the target branch
          update-branch: true
```

#### `azure-build.yml`
This is the action that is supposed to publish the Azure SWA after Retype builds the site and pushes it to the `publish` branch. This file is located in the `main` branch. However, it is not being pushed to the `publish` branch. Instead, the `azure-SWA-HASH.yml` is being pushed.
```
name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - publish  # Trigger on changes to the publish branch
  workflow_dispatch: # Allow manual runs

jobs:
  deploy:
    name: Deploy to Azure Static Web Apps
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the publish branch
      - name: Checkout Publish Branch
        uses: actions/checkout@v3

      # Step 2: Deploy to Azure
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_SECRET }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Root directory contains the built content
          api_location: "" # No API
          output_location: "" # No additional build step
```

#### `azure-SWA-HASH.yml`
This file was automatically generated by Azure when the SWA was being setup (in Azure). This is not used, but was kept just in case.
```
name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - publish  # Trigger on changes to the publish branch
  workflow_dispatch: # Allow manual runs

jobs:
  deploy:
    name: Deploy to Azure Static Web Apps
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the publish branch
      - name: Checkout Publish Branch
        uses: actions/checkout@v3

      # Step 2: Deploy to Azure
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_SECRET }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Root directory contains the built content
          api_location: "" # No API
          output_location: "" # No additional build step
```

#### `.gitignore`
Initially, the `asure-publish.yml` file was not in the ignore (nor `azure-SWA-HASH.yml`). Both were added for testing purposes. Setting or changing this did nothing.
```
/.github/workflows/azure-publish.yml
/.github/workflows/azure-SWA-HASH.yml
```
