### ISSUE TITLE
Migrating from Gitbook

### ISSUE THREAD

**Issue by LoneDev6** [retypeapp/retype#203]
Hello!
Would be nice to get a tutorial or (if needed) a tool/command to convert Gitbook repositories to retype.
An example of Gitbook repository: https://github.com/LoneDev6/Wiki-ItemsAdder
This is the online version: https://itemsadder.devs.beer/

Thanks a lot!

**Comment by geoffreymcgill** [comment]
Hello @LoneDev6. We should write a full guide, but in general Retype will automatically handle a GitBook repository no problem. The functionality to support GitBook is built into Retype.

Just install Retype on your machine and then run the command `retype watch`. That will build your documentation using the `.md` files provided by GitBook. 

I cloned your repo and ran `retype watch` on it. That is all. The conversion took at most a couple seconds. Here is the output:

<img width="1428" alt="Screen Shot 2021-11-16 at 7 12 28 AM" src="https://user-images.githubusercontent.com/62210/141931573-52f138c6-4b9f-41e4-b055-9f98b235b4d3.png">

GitBook still holds some of the data within their database and does not include in the exported `.md` files, so you might want to make a few edits to the `retype.yml` to adjust configs such as the `branding.title` and `links`. 

Here's a new `retype.yml` to test with where configured a [title](https://retype.com/configuration/project/#title), some top navigation [links](https://retype.com/configuration/project/#links), and added your logo into a new `static/logo.png` folder.

```yml
input: .
output: .retype
url: https://itemsadder.devs.beer/
branding:
  title: ItemsAdder Wiki
  logo: static/logo.png
links:
- text: Donation
  link: donation-support-my-work.md
  icon: heart
- text: Addons
  link: https://addons.plugin.ga/itemsadder
  icon: plus
- text: More Plugins
  link: https://plugin.ga/
  icon: plug
- text: Support
  link: /support/ask-for-help.md
  icon: issue-opened
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."
```

You can use the GitBook generated `SUMMARY.md` file to control the left navigation, but a much more robust approach is to use the [`order`](https://retype.com/configuration/page/#order) config.

I created a `retype-test` branch of your repo and did some simple configuration of the `order` and `icon` for pages and folders. Here's what it looks like now:

<img width="1429" alt="Screen Shot 2021-11-16 at 7 14 09 AM" src="https://user-images.githubusercontent.com/62210/141932023-03a26d7d-d705-4690-929e-15e9ce353529.png">

Retype does a good job of upgrading the website from GitBook, but there is always more we can do to automate the process. If you have any suggestions, please feel free to reach out and we'll definitely take a look. 

Hope this helps get you started!
