### ISSUE TITLE
Branding: Label color and background don't work per example

### ISSUE THREAD

**Issue by RickCogley** [retypeapp/retype#208]
Hi - per this example <https://retype.com/configuration/project/#colors>, the yaml has the color and background of the label just as plain text, but that does not work as of 1.11. 

Putting them in quotes fixes it, but it should say so in the manual. FYI. 

This works: 

```
branding:
  title: イソリア
  label: ヘルプ
  logo: /static/eSolia_Square_Chicklet_Logo_YellowBlue.svg
  colors:
    label:
      text: "#ffffff"
      background: "#ff0000"
```
