### ISSUE TITLE
Input path not respected in edit link.

### ISSUE THREAD

**Issue by ddnexus** [retypeapp/retype#283]
I have a [repo](https://github.com/ddnexus/pagy) with a `docs` dir where I use a regular jekyll template to produce this [static site](https://ddnexus.github.io/pagy).

Thinking about migrating to retype, I discovered that the `edit` link does not respect the `input` path. I can move the `retype.yml` from the root dir `input: docs` to the docs dir `input: .` and there is no difference.

Is there any workaround that allow me to keep the doc in the same branch and in the same dir as it is now?

**Comment by geoffreymcgill** [comment]
Hi @ddnexus. Please give the following `edit` configuration a try:

```yml
edit:
  repo: "https://github.com/ddnexus/pagy"
  base: /docs
  branch: master
```

The above adds the [`base`](https://retype.com/configuration/project/#base) and [`branch`](https://retype.com/configuration/project/#branch) configuration. By default, Retype will link to the `main` branch in your repo.

I tested your repo with the following basic `retype.yml` and it appears to work well. This `retype.yml` was placed in the root of the project, but you can of course move inside the `/docs` folder, although just adjust the [`input`](https://retype.com/configuration/project/#input) path as needed.

```yml
input: ./docs
output: .retype
url: "https://ddnexus.github.io/pagy"
branding:
  title: Pagy
  label: Docs
edit:
  repo: "https://github.com/ddnexus/pagy"
  base: /docs
  branch: master
links:
- text: Gitter
  link: https://gitter.im/ruby-pagy/Lobby
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."
```

Hope this helps.
