### ISSUE TITLE
How to set up og:image and twitter:image?

### ISSUE THREAD

**Issue by tempe-techie** [retypeapp/retype#284]
Hi, I see the Retype website has og:image setup, but I can't find instructions on this anywhere in the docs:

```html
<meta property="og:image" content="https://retype.com/static/project-branding-title.png">

<meta property="twitter:image" content="https://retype.com/static/project-branding-title.png">
```

How do I set this up? 🙂

**Comment by geoffreymcgill** [comment]
Hi @tempe-techie. Thanks for the question. 

By default, Retype will try to find the first image on the page and use that image as the feature image. 

You can override the image on a per-page basis by setting the [`image`](https://retype.com/configuration/page/#image) config. 

```yml
---
image: /static/my-custom-image.png
---
# Example Page

Sample paragraph.
```

Hope this helps.

**Comment by tempe-techie** [comment]
Ok, thanks, it worked - adding an image to the main page auto-added it to og and twitter tags 🙂 

Just an idea, maybe in the future `og` and `twitter` metadata could be added to the `meta` part of the config file, something like this:

```yaml
meta:
  title: " | My Website"
  og:
    type: website
    title: "My great website"
    description: "Welcome to my website"
    image: "./static/cover.png"
```
