### ISSUE TITLE
Losing template style when deploying with Github page

### ISSUE THREAD

**Issue by PhongVu07** [retypeapp/retype#314]
This is how my Retype page looks in local environment:
![Screen Shot 2022-04-04 at 20 59 16](https://user-images.githubusercontent.com/54445063/161560334-0d4b8ab7-5c95-4182-8e9a-1225c2e01b62.png)

And this is how it looks like when deployed with github pages:
![Screen Shot 2022-04-04 at 20 59 23](https://user-images.githubusercontent.com/54445063/161560491-1214619b-f53a-433b-9456-f181bc6d6220.png)

Seems like something disables my Retype template style. What should I do?

**Comment by geoffreymcgill** [comment]
In your GitHub Pages configuration, I believe you have the wrong branch selected. 

https://retype.com/hosting/github-pages/#pick-a-branch

You should choose the `retype` branch.

![image](https://user-images.githubusercontent.com/62210/161588104-638d275a-737e-4c01-9ac6-4784429f9328.png)

I'm also assuming you have the Retype GitHub build action configured as well, by adding the `.github/workflows/retype-action.yml` file.

```yml
name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
```

More instructions available at https://retype.com/guides/github-actions/.

Hope this helps.
