### ISSUE TITLE
Support for overriding the Plausible.io domain

### ISSUE THREAD

**Issue by hypherionmc** [retypeapp/retype#352]
Currently the plausible integration, defaults to plausible.io for the script location, but since Plausible can be self hosted, it would be good to allow users to specify or override the domain from which the script is pulled

**Comment by geoffreymcgill** [comment]
This Plausible [`host`](https://retype.com/configuration/project/#plausiblehost) configuration is now available in the latest release of Retype.

```yml
integrations:
  plausible:
    host: plausible.example.com
```
