### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by PirateSeal** [retypeapp/retype#404]
Hi,

first of all, thanks for this amazing app ! I'll buy a pro licence to support when I'll have enough money to do so.

My question is : 

Is it possible to support multiple languages depending on the domain name in the `retype.yml`file ?

What I mean by that is something like this :

```yml
# Assuming the input property is set such as :
# input: ./src

localisation:
    - url: mydomain.com
      src: /en
    - url: mydomain.fr # Using another domain that redirects to the same host IP
      src: /fr
    - url: de.mydomain.com # Using a subdomain
      src: /de
    - url: mydomain.com/nl # Using a path
      src: /nl
```

- The `src`property would be appended to the `input` one if it exists. If not, I don't know, I did not think about a solution yet 😅
- The `url` property would be used to determine the language as you'd want.

I know there are multiple problems that could show up using this way but it's just to explain my question

I hope you have a great day and thanks for reading !
