### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by noraj** [retypeapp/retype#43]
It would be easier to have a tree structure written in `navbar.yaml` or in the global config file

eg.

```yaml
nav:
  - Home: index.md
  - Cheatsheet:
    - 'Basic concepts': 'cheatsheet/basic-concepts.md'
    - 'Control structures': 'cheatsheet/control-structures.md'
    - Collections: 'cheatsheet/collections.md'
    - Methods: 'cheatsheet/methods.md'
    - 'Object oriented programming': 'cheatsheet/object-oriented-programming.md'
    - 'Modules, mixins and standard classes': 'cheatsheet/modules-mixins-standard-classes.md'
    - Files: 'cheatsheet/files.md'
  - About: 'about.md'
```

rather than having to play with the order meta-data in all files.
