### ISSUE TITLE
Gitlab CI + Gitlab Pages

### ISSUE THREAD

**Issue by noraj** [retypeapp/retype#45]
You wrote a Github Actions + Github pages deploy page. I'd like to PR one for Gitlab CI + Gitlab Pages.

A simple naive CI `gitlab-ci.yml`:

```yaml
image: node:lts-alpine

before_script:
  - npm install --global retypeapp # https://retype.com/guides/getting-started/

pages:
  script:
  - retype build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
```

I'll PR when I'll have fixed this error:

```
$ retype build
events.js:352
      throw er; // Unhandled 'error' event
      ^
Error: spawn /usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype',
  path: '/usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype',
  spawnargs: [ 'build' ]
}
```

**Comment by bountyx** [comment]
Here's an example of mine deploying to Netlify:

```
image: node:12

# All jobs per branch will use this cache
# More info: https://docs.gitlab.com/ee/ci/caching/
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - node --version

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: docs
    url: https://docs.example.com
  only:
    - master
  script:
    - npm install retypeapp
    - npm install netlify-cli
    - (cd ./docs && npx retype build)
    - cat ./custom/style.css >> ./docs/.retype/resources/css/retype.css
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./docs/.retype --prod
```

**Comment by nielsvz** [comment]
> You wrote a Github Actions + Github pages deploy page. I'd like to PR one for Gitlab CI + Gitlab Pages.
> 
> A simple naive CI `gitlab-ci.yml`:
> 
> ```yaml
> image: node:lts-alpine
> 
> before_script:
>   - npm install --global retypeapp # https://retype.com/guides/getting-started/
> 
> pages:
>   script:
>   - retype build
>   - mv site public
>   artifacts:
>     paths:
>     - public
>   only:
>   - master
> ```
> 
> I'll PR when I'll have fixed this error:
> 
> ```
> $ retype build
> events.js:352
>       throw er; // Unhandled 'error' event
>       ^
> Error: spawn /usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
>     at onErrorNT (internal/child_process.js:467:16)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
>     at onErrorNT (internal/child_process.js:467:16)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'spawn /usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype',
>   path: '/usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype',
>   spawnargs: [ 'build' ]
> }
> ```

This works for us by switching to the full node image from the alpine one.

**Comment by geoffreymcgill** [comment]
Hi @nielsvz. Would you mind sharing your Retype Gitlab CI `.yml` config file?

We can create an official page in the docs for GitLab.

**Comment by nielsvz** [comment]
Here is what I did to get this to work, this will publish the output to GitLab Pages when running in the default branch of the repository.

`.gitlab-ci.yml`
```yaml
---
stages:
  - build

pages:
  stage: build
  image: node:lts
  before_script:
    - npm install --global retypeapp
  script:
    - 'retype build --override "{ \"url\": \"$CI_PAGES_URL\" }" --output $CI_PROJECT_DIR/public'
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```

Ensure you set the output directory to `./public` and update `url` to match the [GitLab Pages](https://docs.gitlab.com/ee/user/project/pages/getting_started_part_one.html) documentation. You can do this automatically by leveraging the `--override` and `--output` options.

An example project can be found on GitLab.com [here](https://gitlab.com/nvz/gitlab-pages-retype-example), the built website can be reached [here](https://nvz.gitlab.io/gitlab-pages-retype-example/)
