### ISSUE TITLE
We need a global target blank option for external links

### ISSUE THREAD

**Issue by ddnexus** [retypeapp/retype#465]
If you use Retype as a documentation tool, you want to give the user the freedom to navigate the referenced site without having to remember to use `Ctrl-click` or losing the current documentation page. Simply put: if it is an external reference in a documentation tool it should probably always open a new window/tab.

For that we need a simple global option in order to avoid to remember to add `{target="_blank"}` to hundreds of external links, which is not retype-user friendly and very error prone. We have hundreds of external links, and it would be extremely useful!

It looks like it should be simple to implement, since retype already identify external links and compose them correctly, and since it would be just an option, no harm would be done if you don't want/need to use it.

What do you think?

**Comment by wnelson03** [comment]
Agreed, we should be able to set target to open links in new tab, and noreferrer as well.

**Comment by geoffreymcgill** [comment]
Yes, I want this feature as well. We will try to make it happen.

**Comment by latenitefilms** [comment]
I'd also love to see this!

**Comment by latenitefilms** [comment]
Is there a way to change the target for "regular" markdown links?

For example:

```
[Test](https://test.com)
```

**Comment by wnelson03** [comment]
> Is there a way to change the target for "regular" markdown links?
> 
> For example:
> 
> ```
> [Test](https://test.com)
> ```

`[Discord Developer Portal](https://discord.com/developers/applications){ target="_blank" }`

**Comment by geoffreymcgill** [comment]
You can set the `target` manually on links using the following syntax:

```md
[Test](https://test.com){target="_blank"}
```

We are still going to add a project wide `target` option in a future release.

**Comment by latenitefilms** [comment]
Legends, thanks team!

**Comment by geoffreymcgill** [comment]
A new `outbound` feature has been added to Retype Pro and will be available with the upcoming v3.1 release.

If you have Retype Pro license, Retype will automatically add the `:link-external:` icon to all text links that link to an external domain. These `outbound` links will also open in a new window. 

<img width="454" alt="Screen Shot 2023-07-22 at 1 39 26 PM" src="https://github.com/retypeapp/retype/assets/62210/c33025b5-e398-4322-856e-31b57f6e13c7">

The `outbound` functionality can be easily disabled by setting `enabled: false`. By default, `outbound` is enabled for Retype Pro projects. The `outbound` configuration will be ignored on projects that are not Retype Pro. 

The following `outbound` config options within your projects **retype.yml** file are supported:

```
outbound:
  enabled: true|false # Default is true
  target:  blank # Default is "blank"
  custom:  'rel="noopener noreferrer"' # Default is null/empty
  icon:    link-external # Default is "link-external"
  iconAlign: right|left # Default is right
  exclude:
    - example.com # Exclude specific outbound link patterns
  include:
  - * # Include only specific outbound link patterns, default is include all
```

Using a combination of the `exclude` and `include` configs allows for flexible and granular control over which outbound text links are captured by the Retype `outbound` functionality. For instance, if you only wanted links that pointed to the `example.com` domain to be captured, you could configure the following:

```
outbound:
  include:
  - example.com
```

If you only wanted links that pointed to the `docs.example.com` sub-domain and github.com domain to be captured, you could configure the following:

```
outbound:
  include:
  - docs.example.com
  - github.com
```

If you wanted links that pointed to your primary website, say `my-website.com` to excluded, you could configure the following:

```
outbound:
  exclude:
  - my-website.com
```

Hope this helps.
