### ISSUE TITLE
Broken links in navigation bar while deploying with Github Action and Github Pages

### ISSUE THREAD

**Issue by francesco-plt** [retypeapp/retype#477]
I have a repository with a bunch of markdown files in a subfolder called `docs` (e.g. `docs/01.md`, `docs/02.md`, ...). I set up the action as follows:
```
name: Publish Retype powered website to GitHub Pages

on:
  push:
    paths:
      - docs/*.md
  workflow_dispatch:

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
```
The action runs succesfully, and the retype website is accessible from the `github.io` associated to the repository. The problem is that when I open the link associated to the github page of the repository, I can see only the first markdown file: all the links are broken, and the rest of the files is not accessible. I inspected the page and found that the `a` tags are missing the `href` attribute, for example:
```
<a class="flex flex-1 items-center cursor-pointer"><span class="flex shrink-0 items-center justify-center w-6 h-6 mr-2"><!----></span><span class="text-sm py-1.5">Cybercrime</span></a>
```
I used the same action in another repository with the same content structure, and it is working just fine. More specifically the `a` tags behave like they should:
```
<a class="flex flex-1 items-center cursor-pointer" href="../04-heap/"><span class="flex shrink-0 items-center justify-center w-6 h-6 mr-2"><!----></span><span class="text-sm py-1.5">Heap</span></a>
```
