### ISSUE TITLE
favicon not copied

### ISSUE THREAD

**Issue by noraj** [retypeapp/retype#483]
I your configuration is like

```yaml
branding:
  logo: static/logo.png
favicon: static/favicon.ico
```

When running `retype build` , `static/logo.png` will be copied to the output dir but not `static/favicon.ico`.
