### ISSUE TITLE
ref links and alert don't render properly on phone

### ISSUE THREAD

**Issue by Ravencentric** [retypeapp/retype#490]
![](https://user-images.githubusercontent.com/78981416/216319502-12ae5deb-092e-4df2-8fc7-2d91c3694720.png)
![](https://user-images.githubusercontent.com/78981416/216319912-15ef7bdd-28aa-462c-b7c9-a540c3ab864d.png)
![](https://user-images.githubusercontent.com/78981416/216319924-498b99b0-8962-47a2-b655-3786e0236cf9.png)

**Comment by patricklafrance** [comment]
I also had this issue!

@geoffreymcgill I was wondering if it would be possible to add a option to a Reference Link component to hide the link?

Sometiome they are very long and not that useful for the reader:

![image](https://github.com/retypeapp/retype/assets/794579/e992eee4-5feb-4fc1-bbe9-66f041cf0a56)

**Comment by geoffreymcgill** [comment]
yes, agreed. We need to do something to improve the rendering of the Ref and Alert components.

Avoiding the horizontal scrolling of the Alert component should be a straightforward fix. 

What do with long links in the Ref component will take some thought.

**Comment by cclypeatus** [comment]
Scuffed solution to hiding a ref link on mobile:

```css
@media (max-width: 360px) {
  .mb-6.px-5.py-4.flex.justify-between.relative.border.border-gray-300.rounded.transition-colors.duration-150 > .text-gray-400 {
    display: none;
  }  
}
```

You can inject it site-wide via `_includes/head.html`'s `<style>`
