### ISSUE TITLE
Smart margins for ol and ul

### ISSUE THREAD

**Issue by rab-dev** [retypeapp/retype#537]
You guys are doing a great job and it is super easy to create great looking docs with Retype!

## Problem

I sometimes want to highlight a section on a page with a different background color.
Retype's docs show how to do this for containers using the :sample style.

However, if  I end the content in that section with a `ol` or `ul` there is a noticable gap at the bottom of
the section due to `margin-bottom` on `ol` and `ul` css styling.

## Workaround

My workaround is to remove the margin if the ol or ul is the last-child.
I include this as a rule in _includes/head.html.

```
ol:last-child,
ul:last-child {
  margin-bottom: 0px
}
```
Perhaps it is useful to include something like this in your codebase.

**Comment by geoffreymcgill** [comment]
Thanks for the pro tip. 

The following is a sample demonstrating the entire scenario.

First, here is a screen capture of the finished page in a web browser, pointing out where the tighter `bottom-margin` is being applied.

<img width="572" alt="Screenshot 2023-05-09 at 6 11 43 AM" src="https://github.com/retypeapp/retype/assets/62210/dcc32995-8df1-4aea-a9fb-0b79ca428715">

There are 3 files used in this demonstration, `sample.md`, `static/custom.css`, and `_includes/head.html`:

### sample.md

~~~md
# Container sample

This is a sample to demonstrate adding a custom [`:::container`](https://retype.com/components/container) component to style a section of content.

:::custom-gray
This section should have a **lightgray** background color.

- Item one
- Item two
- Item three
:::

The following is a paragraph of text between the lists to demonstrate the default margins.

:::custom-blue
This section should have a **lightblue** background color.

- Item one
- Item two
- Item three
:::

There should be less margin below the list in the **lightblue** section.

By placing the content section in a container with a custom CSS class, you can override the default `margin-bottom`.

The following sample demonstrates the **custom.css** file used in this sample:

```css custom.css
.custom-gray {
    background-color: lightgray;
    border-radius: 8px;
    padding: 12px;
}

.custom-blue {
    background-color: lightblue;
    border-radius: 8px;
    padding: 12px;
}

.custom-blue ol:last-child,
.custom-blue ul:last-child {
  margin-bottom: 0;
}
```

Here is the **lightgray** section demonstrating how to configure the `:::custom-gray` container:

```md
:::custom-gray
This section should have a **lightgray** background color.

- Item one
- Item two
- Item three
:::
```

Here is the **lightblue** section demonstrating how to configure the `:::custom-blue` container:

```md
:::custom-blue
This section should have a **lightblue** background color.

- Item one
- Item two
- Item three
:::
```
~~~

### static/custom.css

```css
.custom-gray {
    background-color: lightgray;
    border-radius: 8px;
    padding: 12px;
}

.custom-blue {
    background-color: lightblue;
    border-radius: 8px;
    padding: 12px;
}

.custom-blue ol:last-child,
.custom-blue ul:last-child {
  margin-bottom: 0;
}
```

### _includes/head.html

```html
<link href="static/custom.css" rel="stylesheet" />
```

Hope this helps.
