### ISSUE TITLE
Responsive columns / image gallery

### ISSUE THREAD

**Issue by DannyBen** [retypeapp/retype#550]
I am trying to find out what is my best option for creating image thumbnails that I want to appear side by side in desktop resolution, and one under the other in mobile resolution.

I was hoping to have a responsive Columns component (flex / grid based), but I noticed it does change its column layout on mobile.

Is there any recommendation for responsive layout for this use case?
If there is no such straight forward solution - perhaps you would consider making the Columns responsive?

**Comment by geoffreymcgill** [comment]
Hi @DannyBen. Responsive columns are not currently supported with the [Column](https://retype.com/components/column) component, but it is certainly something that should be. We will try and implement in a future release.

**Comment by DannyBen** [comment]
Thank you. As a workaround, I have added this as a custom CSS:

```css
  .gallery {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 10px;
  }

  .gallery figure img { 
    height: 100%;
    width: 100%;
    max-height: 30vh;
    object-fit: cover;
    object-position: center;
  }

  @media (max-width: 767px) {
    .gallery {
      grid-template-columns: 1fr;
    }
  }
```

and this as an HTML-in-markdown:

```html
<div class='gallery'>
  <figure>
    <img src='img/1.jpg'/>
    <figcaption class='caption'>Hello</figcaption>
  </figure>
  <figure>
    ...
  </figure>
</div>
```

this lets me piggyback on the native Retype styling of an image + caption.
