### ISSUE TITLE
CSS for Dark Mode?

### ISSUE THREAD

**Issue by latenitefilms** [retypeapp/retype#564]
I currently have this custom CSS in my `head.html`:

```html
<style>
    .review {
        text-align: left;
        color: #1956AF;
        border-radius: 10px;
        background-color: #E1EDFF;
        border: 1px solid #1956AF;
        margin-bottom: 20px;
        padding-top: 15px;
        padding-left: 10px;
        padding-right: 10px;
        padding-bottom: 0px;
    }
    .review p {
        font-size: 11px;
    }
    .review-rating {
        margin-bottom: 5px;
    }
</style>
```

...which I use like this:

```lua
:::review
{{ include "five-stars.md" }}

Excellent addition to FCP
This is a great tool. I have my clients make notes on Vimeo, and Marker Toolbox lets me download a .csv of those comments and create markers on the FCP project/timeline at the proper locations, with notes visible and that will follow the clips as I move them. Once downloaded and installed it's easy. Downloading the .csv and running it through Marker Toolbox and adding the Markers to the project/timeline takes less than a minute, then you're ready to go. Really great find!

_Robert heinlein's son – May 31, 2023 (Apple App Store Review)_
:::
```

It looks great in light mode, but very bright in dark mode.

Is there an easy way to have a seperate `background-color` for dark mode?

**Comment by latenitefilms** [comment]
@geoffreymcgill - Did you have any thoughts on this one? I'm assuming there's just some "dark" class or something I can use? I've tried, but haven't worked it out yet.

**Comment by geoffreymcgill** [comment]
In dark mode, the `dark` css class is added to the `<html>` tag, so you can define dark mode classes like the following:

```css
.review {
    text-align: left;
    color: #1956AF;
    border-radius: 10px;
    background-color: #E1EDFF;
    border: 1px solid #1956AF;
    margin-bottom: 20px;
    padding-top: 15px;
    padding-left: 10px;
    padding-right: 10px;
    padding-bottom: 0px;
}
html.dark .review {
    background-color: red;
    color: white;
}
```

I'm using exaggerated colours in sample `html.dark .review` css class just as an example. Please adjust the colours and styles as per your requirements. 

Hope this helps
