### ISSUE TITLE
Hierarchy of websites

### ISSUE THREAD

**Issue by patricklafrance** [retypeapp/retype#592]
Hello!

We are looking at building a hierarchy of websites for all our library projects, similar to what Adobe is doing with [React Spectrum](https://react-spectrum.adobe.com/index.html):

![image](https://github.com/retypeapp/retype/assets/794579/af42db60-ea2e-4d22-9c18-e66e9b855e74)

The mecanism to link the sites is quite basic, they add a link to return to the root site before the branding icon of every nested site:

![image](https://github.com/retypeapp/retype/assets/794579/de222de1-409c-47e2-b6ad-8f6c9530f7cd)

I would like to have an option with Retype to add such a link before the header icon. I would gladly buy an Enterprise license for that feature.

Thank you,

Patrick

**Comment by geoffreymcgill** [comment]
Interesting idea. Thanks for sharing.

I'm going to look into this. 

What do you think the project config in the `retype.yml` should be called? We have the `url` config which represents the URL of the current project. 

Config name options could be `rootURL` or `root`. Neither seem ideal and could be easily confused with other functionality.

**Comment by geoffreymcgill** [comment]
Initial UI mockup...

https://github.com/retypeapp/retype/assets/62210/7dcccff5-a169-49f1-947f-6ca1830fe414

The current thought is to name this feature the `hub` config:

```yml
hub:
  link: retype.com
  label: Go to retype.com
```

Other options could be be:

```yml
hub:
  link: example.com # default is empty
  label: Home # default is "Home", locale specific
  icon: /static/hub.svg # custom image
  target: blank # default is empty
```

And we might be able to build in the option for a simplified version of the config:

```yml
hub: retype.com
```

If `link` or `hub: <url-here>` is not set, then the "hub link" would not added.

The scenario above assumes I'm on a fictional `docs.retype.com` and I could use the Hub link to jump to the main `retype.com` website, or to another documentation hub. The URL of the hub link could be set to any external or internal URL.

Other possible names for this feature and config name could be:

```
home
root
jump
base
anchor
hub
```

Let me know what you think.
