### ISSUE TITLE
How to add Meta Description for each pages?

### ISSUE THREAD

**Issue by blakstrox** [retypeapp/retype#638]
I tried to add meta description using `meta.description` just like `meta.title`. But it not working.

I tried to add the below information to a page containing profile documentation and it never works

```
---
icon: person
title: My Profile Page
meta:
  title: "Profile Page"
  description: "Profile Meta Description"
---
# Profile
```

**Comment by geoffreymcgill** [comment]
As noted by @paralexm, the [`description`](https://retype.com/configuration/page/#description) should be added on the root level of the page config, which I admit is confusing. 

```yml
---
icon: person
title: My Profile Page
meta:
  title: "Profile Page"
description: "Profile Meta Description"
---
# Profile
```

The [`description`](https://retype.com/configuration/page/#description) setting was supported since the first public release of Retype, whereas the [`meta.title`](https://retype.com/configuration/page/#title) setting was not included until recently with the [v3.0.0](https://retype.com/changelog/#v300) release.

We should likely add `meta.description` too and only support the root `description` for backwards compatibility reasons.
