### ISSUE TITLE
Folder Names With Numbers Result In Incorrectly Displayed name 

### ISSUE THREAD

**Issue by mmalcolmprismcontrols** [retypeapp/retype#650]
Retype version 3.5.0, installed with dotnet.

retype.yml file:
```yml
input: .
output: .retype
branding:
  title: CLI
  label: Docs
links:
- text: Getting Started
  link: https://retype.com/guides/getting-started/
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."
```

My directory tree:
```
└── /repo_root/
    └── docs/
        └── Usage/
```

When I rename the Usage folder to anything starting with a number followed by a dot (e.g: 1. Usage OR 2. Usage or 3. Usage, I see the HTML elements instead of the actual folder name:

![image](https://github.com/retypeapp/retype/assets/126725772/40758916-dd39-4c89-b314-3ecdb3ab9dd7)
