### ISSUE TITLE
Project custom links: Add title attribute

### ISSUE THREAD

**Issue by conanthedev** [retypeapp/retype#672]
With the project top menu [custom links](https://retype.com/configuration/project/#links) we can set text, icon, alignment and target. It would be useful if we could also provide a title attribute like this:

`retype.yml`

```yaml
links:
- text: Getting Started
  link: https://retype.com/getting_started/
  title: Some custom title shown in the hyperlink tooltip
```
