### ISSUE TITLE
Page metadata: Add keywords to use with retype search

### ISSUE THREAD

**Issue by conanthedev** [retypeapp/retype#673]
Is there a way we can add hidden keywords to a page that the retype search will use?

Something like this in the [page configuration](https://retype.com/configuration/page/#page-configuration) would be very useful:
```yml
---
label: Sample
layout: page
order: 100
keywords:
  - hidden keyword
  - second hidden keyword
---
# Sample

This is a sample page demonstrating page metadata.
```
