### ISSUE TITLE
Issues deploying with Docker

### ISSUE THREAD

**Issue by Liege72** [retypeapp/retype#678]
I'm having some issues hosting my retype instance and I think the problem lies somewhere between my computer, the docker container I'm building, and the server I am deploying to. 

1. I tried using a cloudflare tunnel servicing "HTTP://localhost:5050" and serving the `5050` port in the retype.yml configuration file.
2. After this failed, I thought the issue was the tunnel conflicting with apache, so I deleted it and just created an A record.

Neither of these approaches have worked and currently my error is a 525 (SSL handshake failed).

My configuration files and stuff are below

**retype.yml**
```yaml
input: .
output: .retype
url: ted.liege.dev
branding:
  title: TED
  label: Docs
  logo: /favicon.png
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."
favicon: /favicon.png
serve:
  port: 5050
```

**Dockerfile**
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS builder
WORKDIR /build
COPY . /build
RUN dotnet tool install retypeapp --tool-path /bin
RUN retype build --output .docker-build/

FROM httpd:latest
COPY --from=builder /build/.docker-build/ /usr/local/apache2/htdocs/
```

**Docker compose file**
```yaml
# this is a block within the services block
  teddocs:
    image: teddocs:0.0.3
    networks:
      - personal_network
    ports:
      - 5050:5050
```
**Screenshot of cloudflare tunnel**
![image](https://github.com/retypeapp/retype/assets/65319395/bc472785-6ce1-4af1-a0bd-e82a41f399ef)

**Logs from docker container**
```
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.24.0.6. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.24.0.6. Set the 'ServerName' directive globally to suppress this message
[Thu Jan 25 20:54:41.165141 2024] [mpm_event:notice] [pid 1:tid 140017703307136] AH00489: Apache/2.4.58 (Unix) configured -- resuming normal operations
[Thu Jan 25 20:54:41.165546 2024] [core:notice] [pid 1:tid 140017703307136] AH00094: Command line: 'httpd -D FOREGROUND'
```

The retype instance runs fine locally (on port 5050), just not on the server. Anyone have any ideas on how to fix this?
