### ISSUE TITLE
Not displaying directories containing dots

### ISSUE THREAD

**Issue by maurxce** [retypeapp/retype#703]
Hello! I just started trying out Retype and I believe I have found an issue regarding directory names.

# Usual Behavior
1. `mkdir directory`
2. Side panel shows new directory "Directory"

# Behavior when directory contains dots
1. `mkdir test.d`
2. Side panel does not pick up new directory

The website does refresh though, so it is picking up *something*, just not displaying it.

# Docker compose
```yaml
services:
  retype:
    image: retypeapp/retype
    volumes:
      - ./app:/retype
    ports:
      - 5000:5000
    command: retype start
```
I'm using the latest version pushed to `hub.docker.com`.
