### ISSUE TITLE
Lowercase directory name not working

### ISSUE THREAD

**Issue by maurxce** [retypeapp/retype#704]
Hello, I'm currently struggling to make my directory names be lowercase.
I have tried the following, but none of these worked:
```yaml
# retype.yml
generator:
  recase: none
```
```yaml
# directory/index.y(a)ml
---
label: lowercase.label
---
```
```yaml
# directory/index.y(a)ml
---
label: "lowercase.label"
---
```
Is there something I'm missing?
