### ISSUE TITLE
GitHub Action Failure

### ISSUE THREAD

**Issue by latenitefilms** [retypeapp/retype#711]
I'm seeing this today, but no idea why:

```
Run retypeapp/action-build@latest
  with:
    license: ***
Run ${GITHUB_ACTION_PATH}/build.sh
  ${GITHUB_ACTION_PATH}/build.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_OVERRIDE_TITLE: 
    INPUT_OVERRIDE_BASE: 
    INPUT_LICENSE_KEY: ***
    INPUT_STRICT: 
    INPUT_CONFIG_PATH: 
Working directory is: /home/runner/work/FCPCafe/FCPCafe
Installing Retype v3.6.0 using dotnet tool: done.
Determining temporary target folder to place parsed documentation: /tmp/tmp.7ixvsA6mKa
Setting up build arguments: locate, /docs/retype.yml, license key, done.
Building documentation: error.
Error: retype build command failed with exit code 1.
Failed command and output:

$ retype build --verbose docs/retype.yml --secret *** --override {
  "output": "/tmp/tmp.7ixvsA6mKa"
}

You must install or update .NET to run this application.

App: /home/runner/.dotnet/tools/retype
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: /usr/lib/dotnet

The following frameworks were found:
  8.0.8 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=ubuntu.24.04-x64&os=ubuntu.24.04
----

Aborting documentation build process.
Error: Process completed with exit code 1.
```

https://github.com/CommandPost/FCPCafe/actions/runs/11353317459/job/31578090823

**Comment by geoffreymcgill** [comment]
Thanks for the report. I'm looking into it right now and will try to reproduce.

**Comment by geoffreymcgill** [comment]
@latenitefilms Can you point me to a GitHub repo that is failing?

**Comment by latenitefilms** [comment]
See: https://github.com/CommandPost/FCPCafe/actions

**Comment by geoffreymcgill** [comment]
I'm not entirely sure why the action is failing and I haven't been able to reproduce, but can you try adding the following config into your `retype-action.yml` file around [line 142](https://github.com/CommandPost/FCPCafe/blob/86e316895370138b1ad867a6abef8fe58c577b87/.github/workflows/retype-action.yml#L142).

### Existing

```
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Build and publish using Retype
        uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_SECRET }}
```

### Revised

```
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build and publish using Retype
        uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_SECRET }}
```

The configuration should not be required, but for some reason Retype is failing to run under the default `runs-on: ubuntu-latest` environment.

I am still investigating.
