### ISSUE TITLE
Author + avatar sometimes showing twice per page

### ISSUE THREAD

**Issue by 7MinSec** [retypeapp/retype#724]
Hello,

I deployed Retype in GitHub pages and it's working great!  I have this weird issue though where a few of my pages (all built on a simple .md template) show my authorship twice even though it only appears once in the file:

```
---
authors:
  - name: Brian Johnson
    link: https://blahblah
    avatar: http://blahblah
icon: tools
label: Security appliance install

---
```
This shows as:

![Image](https://github.com/user-attachments/assets/15a8946b-7f22-4b53-84fa-46b76b6e0845)

Any thoughts?
