### ISSUE TITLE
Can /blog page include left sidebar?

### ISSUE THREAD

**Issue by 7MinSec** [retypeapp/retype#729]
Hello,

Is there a way to setup `/blog` so that the left side menu *does* appear?  I tried making an `index.md` in the `/blog` folder and played with some other options but couldn't get it to go.  Feel like I'm missing something simple.

![Image](https://github.com/user-attachments/assets/f5a3ac85-b279-4666-9163-7b28541a857b)

Thanks,
Brian

**Comment by latenitefilms** [comment]
I'd also love to see this option @geoffreymcgill !

**Comment by latenitefilms** [comment]
@geoffreymcgill - Let me know if this is on the roadmap, otherwise I'll just try solve it with GitHub Actions. Thank you!

**Comment by geoffreymcgill** [comment]
I don't think this layout is possible with the current settings. Adding the functionality is possible, although not currently scheduled for development.

**Comment by latenitefilms** [comment]
Amazing, THANK YOU! Just tweaked on FCP Cafe - so will check it out soon!

**Comment by geoffreymcgill** [comment]
@latenitefilms I think you will need the following revisions:

### 1. retype.yml

Add the following `layout` setting to your project `retype.yml` file:

```yml
blog:
  pageSize: 50
  layout: page
```

### 2. Remove `layout` from blog posts

Remove the `layout: blog` configuration from all blog post pages. This change will allow the new `blog.layout` property to set the default layout to use for all blog posts within the `/blog/` folder. 

```
---
title: Unreal Fest - 30th June 2023
date: 2023-06-30
author:
  name: Chris Hocking
  avatar: https://fcp.cafe/static/chrishocking.jpg
# layout: blog # <--- remove this line from all blog posts
---
# 30th June 2023
```

### 3. Add `blog/index.md`

Add the following file `blog/index.md` file:

```yml
---
label: Off-topic Rants
icon: squirrel
order: 8899
image: /static/thumbnail.jpg
---
# Off-topic Rants

This is a very random collection of old blog posts from the original LateNite blog, Unreal Cafe, Resolve Cafe and Chris Hocking's past personal blogs.
```

### 4. Delete `off-topic-rants.md`

Delete the file `docs/off-topic-rants.md`

---

With the 4 updates above, you should get the same sidebar tree navigation and the blog posts should all render in the `page` layout.

Hope this helps.
