### ISSUE TITLE
Error for github action: .NET 7.0 is no longer supported

### ISSUE THREAD

**Issue by johnmeah** [retypeapp/retype#739]
Error for github action:
.NET 7.0 is no longer supported and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the .NET sup

Action code:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

Fix Implemented:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

Please provide the appropriate fix if this is incorrect.

**Comment by andesco** [comment]
I ran into this wall just now and manually fixed as follows:

```yaml
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
```

The next release (3.7) appears to solve for this with [commit 1387923]( https://github.com/retypeapp/retype/commit/13879231d9ddba0cdd195cae3bd9caaa5c2c3bcf#diff-855b9ae3cb250e00893f318ef2fdc276064e5204f0945af332a4792aadca6ed8).

**Comment by geoffreymcgill** [comment]
Retype v3.7.0 has been released. If you are using the `@latest` tag, you no longer require the `setup-dotnet` section in your workflow. The following section can be removed:

```yaml
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
```

The default `retype-action.yml` sample has been updated at the following location, see

https://retype.com/guides/github-actions/#step-1-add-retype-actionyml-workflow

```yaml
name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
```

Hope this helps.
